### ISSUE TITLE
translate the screenshot

### ISSUE THREAD

**Issue by SunnyDeng** [MicrosoftDocs/ATADocs.cs-cz#23]
can you translate the screenshot?

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: c89d6c0f-0950-88ca-4530-3b309526213f
* Version Independent ID: 87f5118f-d246-46c5-7711-8e2de2606b33
* Content: [Instalace Advanced Threat Analytics – krok 6](https://docs.microsoft.com/cs-cz/advanced-threat-analytics/install-ata-step6)
* Content Source: [ATADocs/install-ata-step6.md](https://github.com/MicrosoftDocs/ATADocs.cs-cz/blob/live/ATADocs/install-ata-step6.md)
* Service: ****
* Product: **advanced-threat-analytics**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by CeciAc** [comment]
@SonjaSaltzman @nokura 
@SunnyDeng created this as a test a while ago, can you check if this is still valid or should we do something about it?
kind regards

**Comment by SonjaSaltzman** [comment]
@SunnyDeng @nokura  I'm closing this issue; not sure why the screenshot should be loc'd (it's out of scope I think).
